version: "3.3"
services:

  grafana:
    image: grafana/grafana
    networks:
      - traefik-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.entrypoints=http"
      #- "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.http.routers.grafana_http.rule=Host(`grafana.local`)"
      #- "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
      #- "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.forceslash=true"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
