version: '3.2'

services:
  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
      - traefik-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer-ce
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    #ports:
    #  - "9000:9000"
    #  - "8000:8000"
    volumes:
      - portainer_data:/data
    networks:
      - agent_network
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=http"
      #- "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer_http.rule=Host(`portainer.local`)"
      #- "traefik.http.routers.portainer.rule=PathPrefix(`/portainer`)"
      #- "traefik.http.routers.portainer.middlewares=portainer-stripprefix"
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.prefixes=/portainer"       
      #- "traefik.http.middlewares.portainer-stripprefix.stripprefix.forceslash=true"
      - "traefik.docker.network=traefik-net"

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-net:
    external: true

volumes:
  portainer_data:
